<?php

use Drupal\user\Entity\User;
use Drupal\file\Entity\File;

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function docchula_auth_user_delete(User $user) {
  if (user_picture_enabled()) {
    $user_picture_id = $user->get('user_picture')->first()->getValue()['target_id'];
    if ($user_picture_id) {
      $file = File::load($user_picture_id);
      $file->setTemporary();
      $file->save();
    }
  }
}
