version: "3.7"

services:
  drupal:
    image: docker.pkg.github.com/mdcuresearchclub/web/mdcuresearchclub-web
    networks:
      - default
      - main
    secrets:
      - postgres_password
      - drupal_hash_salt
      - google_auth
    volumes:
      - drupal_files:/var/www/html/web/sites/default/files
      - drupal_private_files:/var/www/html/files
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  drupal_files:
  drupal_private_files:
  postgres_data:

secrets:
  drupal_hash_salt:
    external: true
  postgres_password:
    external: true
  google_auth:
    external: true

networks:
  main:
    external: true
    name: Main_default
