version: "3.7"

services:
  drupal:
    image: docker.pkg.github.com/mdcuresearchclub/web/mdcuresearchclub-web
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - drupal_files:/var/www/html/web/sites/default/files
  postgres:
    image: postgres
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  drupal_files:
  postgres_data:

secrets:
  postgres_password:
    external: true

networks:
  default:
    external: true
    name: Main_default
